/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package panel;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Alex
 */
public class EndingPanel extends javax.swing.JPanel {

    private Icon[] chIMGs;
    private Icon[] walkIMGs;
    private Icon[] liftIMGs;
    private Icon[] liftStillIMGs;
    private Icon bodyIMG = new javax.swing.ImageIcon(getClass().getResource("/panel/image/dead_julian_reverse.png"));
    private Icon cubeIMG = new javax.swing.ImageIcon(getClass().getResource("/panel/image/cube.gif"));
    public int imgID;
    
    
    /**
     * Creates new form EndingPanel
     */
    
    private static EndingPanel endingSingle;
    
    private EndingPanel() {
        initComponents();
        
        bodyLabel.setIcon(bodyIMG);
        
        chIMGs = new Icon[5];
        chIMGs[0] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/stand_freeze.gif"));
        chIMGs[1] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/stand_firen.gif"));
        chIMGs[2] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/stand_davis.gif"));
        chIMGs[3] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/stand_john.gif"));
        chIMGs[4] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/stand_woody.gif"));
        
        walkIMGs = new Icon[5];
        walkIMGs[0] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/walk_freeze.gif"));
        walkIMGs[1] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/walk_firen.gif"));
        walkIMGs[2] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/walk_davis.gif"));
        walkIMGs[3] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/walk_john.gif"));
        walkIMGs[4] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/walk_woody.gif"));
        
        liftIMGs = new Icon[5];
        liftIMGs[0] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/lift_freeze.gif"));
        liftIMGs[1] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/lift_firean.gif"));
        liftIMGs[2] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/lift_davis.gif"));
        liftIMGs[3] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/lift_john.gif"));
        liftIMGs[4] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/lift_woody.gif"));
        
        liftStillIMGs = new Icon[5];
        liftStillIMGs[0] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/lift_stand_freeze.png"));
        liftStillIMGs[1] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/lift_stand_firen.png"));
        liftStillIMGs[2] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/lift_stand_davis.png"));
        liftStillIMGs[3] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/lift_stand_john.png"));
        liftStillIMGs[4] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/lift_stand_woody.png"));
    }
    
    public static EndingPanel getInstance()
    {
        if(endingSingle == null)
        {
            endingSingle = new EndingPanel();
        }
        return endingSingle;
    }
    
    public void setStandIMG(int id)
    {
        chLabel.setIcon(chIMGs[id]);
        this.imgID = id;
    }
    
    public void setWalkIMG(int id)
    {
        chLabel.setIcon(walkIMGs[id]);
    }
    
    public void setWalkPosition (int x, int y)
    {
        setWalkIMG(this.imgID);
        
        chLabel.setLocation(x, y);
    }
    
    public void setCubePosition (int x, int y)
    {   
        cubeLabel.setIcon(cubeIMG);
        cubeLabel.setLocation(x, y);
    }
    
    public void setLiftIMG (int id)
    {
        chLabel.setIcon(liftIMGs[id]);
    }
    
    public void setLiftPosition (int x, int y)
    {
        setLiftIMG(this.imgID);
        chLabel.setLocation(x, y);
    }
    
    public void setLiftStillIMG (int id)
    {
        chLabel.setIcon(liftStillIMGs[id]);
    }
    
    public void setLiftStillPosition (int x, int y)
    {
        setLiftStillIMG(this.imgID);
        chLabel.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activeLabel = new javax.swing.JLabel();
        cubeLabel = new javax.swing.JLabel();
        bodyLabel = new javax.swing.JLabel();
        chLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(null);

        activeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activeLabelMouseClicked(evt);
            }
        });
        add(activeLabel);
        activeLabel.setBounds(0, 0, 800, 600);

        cubeLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        add(cubeLabel);
        cubeLabel.setBounds(625, 470, 100, 100);

        bodyLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        add(bodyLabel);
        bodyLabel.setBounds(600, 470, 100, 100);

        chLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        add(chLabel);
        chLabel.setBounds(130, 470, 100, 100);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/image/background_level5.gif")));
        add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void activeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeLabelMouseClicked
        // TODO add your handling code here:
        WalkAnimeThd walk = new WalkAnimeThd();
        raiseAnimeThd raise = new raiseAnimeThd();
        walk.start();
        raise.start();
    }//GEN-LAST:event_activeLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeLabel;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel bodyLabel;
    private javax.swing.JLabel chLabel;
    private javax.swing.JLabel cubeLabel;
    // End of variables declaration//GEN-END:variables
}

class WalkAnimeThd extends Thread
{
    private int coordX;
    private int coordY;
    
    public WalkAnimeThd()
    {
        this.coordX = 130;
        this.coordY = 470;
    }
    
    public void run()
    {
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(WalkAnimeThd.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        while (this.coordX <= 600)
        {
            try {
                Thread.sleep(80);
            } catch (InterruptedException ex) {
                Logger.getLogger(WalkAnimeThd.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            this.coordX += 10;
            
            turnWalking();
        }
        turnLifting();
    }

    private void turnWalking()
    {
        SwingUtilities.invokeLater(new Runnable() 
        {
            public void run() 
            {
                EndingPanel.getInstance().setWalkPosition(coordX, coordY);
            }
        });
    }
    
    private void turnLifting()
    {
        SwingUtilities.invokeLater(new Runnable() 
        {
            public void run() 
            {
                EndingPanel.getInstance().setLiftPosition(coordX, coordY);
            }
        });
    }
}

class raiseAnimeThd extends Thread
{
    private int coordX;
    private int coordY;
    
    public raiseAnimeThd()
    {
        this.coordX = 625;
        this.coordY = 485;
    }
    
    public void run()
    {
        try {
            Thread.sleep(5000);
        } catch (InterruptedException ex) {
            Logger.getLogger(raiseAnimeThd.class.getName()).log(Level.SEVERE, null, ex);
        } 
        turnRaising();
        
        while (this.coordY >= 427)
        {
            try {
                Thread.sleep(30);
            } catch (InterruptedException ex) {
                Logger.getLogger(raiseAnimeThd.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            this.coordY -= 3;
            
            turnRaising();
        }
        turnLiftStill();
    }
    
    private void turnRaising()
    {
        SwingUtilities.invokeLater(new Runnable() 
        {
            public void run() 
            {
                EndingPanel.getInstance().setCubePosition(coordX, coordY);
            }
        });
    }
    
    private void turnLiftStill()
    {
        SwingUtilities.invokeLater(new Runnable() 
        {
            public void run() 
            {
                EndingPanel.getInstance().setLiftStillPosition(605, 470);
            }
        });
    }
}
