/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package panel;

import javax.swing.Icon;

/**
 *
 * @author Alex
 */
public class EndingPanel extends javax.swing.JPanel {

    private Icon[] chIMGs;
    
    /**
     * Creates new form EndingPanel
     */
    
    private static EndingPanel endingSingle;
    
    private EndingPanel() {
        initComponents();
        chIMGs = new Icon[5];
        chIMGs[0] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/ch_freeze.png"));
        chIMGs[1] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/ch_firen.png"));
        chIMGs[2] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/ch_davis.png"));
        chIMGs[3] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/ch_john.png"));
        chIMGs[4] = new javax.swing.ImageIcon(getClass().getResource("/panel/image/ch_woody.png"));
    }
    
    public static EndingPanel getInstance()
    {
        if(endingSingle == null)
        {
            endingSingle = new EndingPanel();
        }
        return endingSingle;
    }
    
    public void setIMG(int id)
    {
        chLabel.setIcon(chIMGs[id]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        add(chLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chLabel;
    // End of variables declaration//GEN-END:variables
}
