/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package panel;

import frame.MainFrame;
import littletyper.Music;

/**
 *
 * @author BruceChen
 */
public class NetworkWinPanel extends javax.swing.JPanel {

    /**
     * Creates new form NetworkWinPanel
     */
    private static NetworkWinPanel nwSingle = null;
    private Music netWinMusic = new Music("network_win.wav");
        
    private NetworkWinPanel() {
        initComponents();
    }
    
    public static NetworkWinPanel getInstance()
    {
        if(nwSingle == null)
        {
            nwSingle = new NetworkWinPanel();
        }
        return nwSingle;
    }
    
    public Music getNetWinMusic()
    {
        return this.netWinMusic;
    }
    
    public void Ticking()
    {
        NetWinThread tick = new NetWinThread();
        tick.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel1.setText("You Win!!");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/image/win.png")));
        jLabel2.setText("   ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel2)))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addContainerGap(313, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}

class NetWinThread extends Thread
{
    public void run()
    {
        long startTime = System.currentTimeMillis();
        long endTime = System.currentTimeMillis();
        while( (endTime - startTime) < 5000)
        {
            endTime = System.currentTimeMillis();
        }
        
        PlayingPanel.getInstance().setNeedSwitch(true);
        MainFrame.getInstance().SwitchPanel("start");
        StartPanel.getInstance().getStartMusic().playLoop();
    }
}