/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package panel;
import frame.MainFrame;
import javax.swing.Icon;

/**
 *
 * @author Alex
 */
public class ProloguePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProloguePanel
     */
    private String[] storyTexts;
    //private Icon backgroundIMG;
    private int i = 0;
    
    private static ProloguePanel prologueSingle;
    
    private ProloguePanel() {
        initComponents();
        //backgroundIMG = new javax.swing.ImageIcon(getClass().getResource("/panel/image/prologueBGimg.png"));
        //storyLabel.setIcon(backgroundIMG);
        storyTexts = new String[6];
        storyTexts[0] = "there was @#$%@#$%@";
        storyTexts[1] = "and there was the BOSS  who #@#$%@#";
        storyTexts[2] = "but the !#$!%#@%@";
        storyTexts[3] = "@#$@#^&!&^&$%^*&";
        storyTexts[4] = "THE LITTLE TYPER!!! ";
        storyTexts[5] = "";
    }
    
    public static ProloguePanel getInstance()
    {
        if(prologueSingle == null)
        {
            prologueSingle = new ProloguePanel();
        }
        return prologueSingle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        storyLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jButton1.setText("skip");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(0, 550, 180, 54);

        jButton2.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jButton2.setText("Next");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(620, 550, 180, 50);

        storyLabel.setFont(new java.awt.Font("Impact", 0, 72)); // NOI18N
        storyLabel.setForeground(new java.awt.Color(255, 255, 255));
        storyLabel.setText("Once upon a time ...");
        storyLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        storyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storyLabelMouseClicked(evt);
            }
        });
        add(storyLabel);
        storyLabel.setBounds(0, 0, 800, 600);
        storyLabel.getAccessibleContext().setAccessibleName("  Once upon a time ...");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panel/prologueBGimg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void storyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storyLabelMouseClicked
        // TODO add your handling code here:
        storyLabel.setText(storyTexts[i]);
        
        if (i <= 4)
            i++;// = (i+1) % 5;
        else
        {
           //background music stop
            MainFrame.getInstance().SwitchPanel("character");
            ChoseCharacterPanel.getInstance().choseInit();
            ChoseCharacterPanel.getInstance().getSelectMusic().playLoop();
            i = 0;
            storyLabel.setText("Once upon a time ...");
        }
    }//GEN-LAST:event_storyLabelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainFrame.getInstance().SwitchPanel("character");
        ChoseCharacterPanel.getInstance().choseInit();
        ChoseCharacterPanel.getInstance().getSelectMusic().playLoop();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        storyLabel.setText(storyTexts[i]);
        
        if (i <= 4)
            i++;// = (i+1) % 5;
        else
        {
           //background music stop
            MainFrame.getInstance().SwitchPanel("character");
            ChoseCharacterPanel.getInstance().choseInit();
            ChoseCharacterPanel.getInstance().getSelectMusic().playLoop();
            i = 0;
            storyLabel.setText("Once upon a time ...");
        }
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel storyLabel;
    // End of variables declaration//GEN-END:variables
}
