/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package panel;
import frame.MainFrame;

/**
 *
 * @author Alex
 */
public class ProloguePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProloguePanel
     */
    private String[] storyTexts;
    private int i = 0;
    
    private static ProloguePanel prologueSingle;
    
    private ProloguePanel() {
        initComponents();
        storyTexts = new String[5];
        storyTexts[0] = "there was @#$%@#$%@";
        storyTexts[1] = "and there was the BOSS  who #@#$%@#";
        storyTexts[2] = "but the !#$!%#@%@";
        storyTexts[3] = "@#$@#^&!&^&$%^*&";
        storyTexts[4] = "THE LITTLE TYPER!!! ";
    }
    
    public static ProloguePanel getInstance()
    {
        if(prologueSingle == null)
        {
            prologueSingle = new ProloguePanel();
        }
        return prologueSingle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        storyLabel = new javax.swing.JLabel();

        jButton1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jButton1.setText("skip");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        storyLabel.setFont(new java.awt.Font("Impact", 0, 72)); // NOI18N
        storyLabel.setText("Once upon a time ...");
        storyLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        storyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storyLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(storyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(storyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        MainFrame.getInstance().SwitchPanel("playing");
    }//GEN-LAST:event_jButton1MouseClicked

    private void storyLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storyLabelMouseClicked
        // TODO add your handling code here:
        storyLabel.setText(storyTexts[i]);
        if (i < 4)
            i++;
        else
            MainFrame.getInstance().SwitchPanel("playing");
    }//GEN-LAST:event_storyLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel storyLabel;
    // End of variables declaration//GEN-END:variables
}
